[package]
name = "secretsanta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.145"
serde_json = "1.0.86"
sha2 = "0.10.6"
base64 = "0.13.0"
rand = "0.8.5"