pub(crate) const HTTP_STATUS_200: &str = "HTTP/1.1 200 OK";
pub(crate) const HTTP_STATUS_400: &str = "HTTP/1.1 400 Bad Request";
pub(crate) const HTTP_STATUS_401: &str = "HTTP/1.1 401 Unauthorized";
pub(crate) const HTTP_STATUS_403: &str = "HTTP/1.1 403 Forbidden";
pub(crate) const HTTP_STATUS_404: &str = "HTTP/1.1 404 Not Found";
pub(crate) const HTTP_STATUS_405: &str = "HTTP/1.1 405 Method Not Allowed";
pub(crate) const HTTP_STATUS_500: &str = "HTTP/1.1 500 Internal Server Error";
pub(crate) const HASH_SALT: &str = "12&$!@#hjkloqwE*";
pub(crate) const PASSWORD_MIN_LENGTH: usize = 8;
